groups:
    - bash
    - developer
recipes:
    mac_os_x:
        - osxdefaults::disable_natural_scrolling
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::set_computer_name
attributes:
    git:
        name: Danny Frade
        email: danny@frade.ca
    osxdefaults:
        computername: fradebase
    sublime_text:
        preferences:
            caret_style: "phase"
            color_scheme: "Packages/Theme - Flatland/Flatland Dark.tmTheme"
            draw_white_space: "selection"
            flatland_sidebar_tree_xsmall: true
            flatland_square_tabs: true
            font_size: 9
            highlight_modified_tabs: true
            margin: 4
            overlay_scroll_bars: "enabled"
            scroll_past_end: true
            shift_tab_unindent: true
            tab_size: 2
            theme: "Spacegray.sublime-theme"
            translate_tabs_to_spaces: true
            word_wrap: false
            font_face: "Monaco"
            fade_fold_buttons: false
            scroll_past_end: true
    homebrewalt:
        cask_apps:
            - versions
            - bartender
            - slack
